---
title: SUN BURST DIAGRAM - 互動式網站流量分析圖
author: 中山大學管理學院 卓雍然
date: "`r Sys.time()`"
output: 
  html_document:
    highlight: pygments
    theme: flatly
    css: style.css
---

```{r results='hide', message=FALSE, warning=FALSE, echo=F}
# 這個區段主要是設定筆記網頁的格式和載入(安裝)一些基本的套件，請大家不要改動
rm(list=ls(all=T))
knitr::opts_chunk$set(comment = NA)
knitr::opts_knit$set(global.par = TRUE)
par(cex=0.8)
options(scipen=20, digits=4, width=90)

if(!require(pacman)) install.packages("pacman")
pacman::p_load(dplyr, readr, stringr, sunburstR)
```
<hr>

### Make Session `SS` & Sequence `SQ` ID's
```{r}
B <- read_csv("data/TBN_CUST_BEHAVIOR.csv") %>% data.frame
```

```{r}
B$rid = 1:nrow(B)
B = B %>% arrange(VISITDATE, CUST_NO)
B$SS = group_indices(B, VISITDATE, CUST_NO)
B = group_by(B, SS) %>% mutate(SQ = row_number()) %>% data.frame
```

```{r}
subset(B, SS == 7)
```
<hr>
 
### Examine the URL's
```{r}
pg = table(B$PAGE) %>% sort(decreasing=T) %>% as.data.frame
rbind(head(pg), tail(pg))
nrow(pg)                                                             # 782
grepl("^http(s)?://www.esunbank.com.tw/", pg$Var1) %>% sum           # 782
gsub("^http(s)?://www.esunbank.com.tw/", "", pg$Var1) %>% n_distinct # 671
```

Some URL start by `http://`
```{r}
str_detect(B$PAGE, "^https://www.esunbank.com.tw/") %>% table
```

Shorten the URL
```{r}
B$HTTPS= str_detect(B$PAGE, "^https://www.esunbank.com.tw/")
B$PAGE = str_replace(B$PAGE, "^http(s)?://www.esunbank.com.tw/", "")
```
<hr>

### Sun-Burst : URL Hierarchy
<span style="font-size:24px">`r "\U1F4A1"`:</span> 
Sun-Burst Diagram 是網站流量資料最好的視覺化工具之一
```{r}
pages = B$PAGE %>% 
  str_replace_all("-", "_") %>% 
  str_replace_all("/", "-") %>% 
  table %>% sort(decreasing=T) %>% as.data.frame
head(pages)
```

```{r}
sunburst(subset(pages, Freq > 10))
```
<hr>

### Working on Session & Sequence 

```{r}
B$PAGE = str_replace(B$PAGE, "/$", "")
n_distinct(B$PAGE)
```

```{r fig.height=5, fig.w=8}
p0 = par(cex=0.8, mar=c(5,25,3,2))
table(B$PAGE) %>% sort(decr=T) %>% head(20) %>% barplot(horiz=T, las=2)
```

```{r}
PAGES = table(B$PAGE) %>% sort(decr=T)
```

```{r}
sapply(0:10, function(i) sum(PAGES > i))
# 611 573 557 541 522 508 501 490 482 476
```

```{r}
B$PAGE =  factor(B$PAGE, levels=names(PAGES))
```

```{r}
S = B %>% 
  mutate(pid = as.integer(PAGE)) %>% 
  group_by(SS) %>% 
  summarise(
    npage = n(),
    seq = paste0('P',pid,collapse="-")
    ) %>% ungroup() %>% data.frame
```

```{r}
save(B, S, file = "data/ys.rdata")
```


##### No. pages in the sessions
```{r}
table(S$npage) %>% sort %>% tail(10)
```

```{r}
sapply(1:10, function(i) mean(S$npage > i)) %>% round(2)
```

##### The most frequent sequence
```{r}
table(S$seq) %>% sort %>% tail(20)
```
<hr>

### Bounced Sequences (`npage == 1`) 
```{r}
table(subset(S, npage == 1)$seq) %>% sort %>% tail(30)
```

### Sequences longer than One (`npage > 1`) 
```{r}
page2 = table(subset(S, npage > 1)$seq) %>% sort 
```

```{r}
sum(page2 > 50)
```

```{r}
sapply(seq(100,500,100), function (i) sum(tail(page2, i))/sum(page2) )
```

##### The 100 most freq sequences (43.1%)
```{r}
p100 = data.frame(page2) %>% tail(100)
sunburst(p100)
```


<br><br>